### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by MitchTalmadge** [3zmana/chocolateypackages#1]
Hey there!

I noticed the README says "Packages abandoned". I assume you are no longer maintaining these packages. Would you be open to adding me as a maintainer for NetSetMan? I would be happy to take over maintenance for that package in a new GitHub repository. 

Thanks!

**Comment by 3zmana** [comment]
Hi!
Yes gladly, I don't have time to maintain the NetSetMan package at the moment.
I would just ask you to let me maintain the package on Chocolatey, so that if one day you can't maintain it anymore I can add another maintainer. As you can see, I am still reactive even after several years of inactivity!
What is your exact username on chocolatey ?

**Comment by MitchTalmadge** [comment]
Cool, that sounds good to me! My username on Chocolatey is MitchTalmadge

Thanks!

**Comment by 3zmana** [comment]
You have been added to chocolatey !
Thank you for your participation in the Chocolatey community !
